### ISSUE TITLE
Issues after update of esphome

### ISSUE THREAD

**Issue by CheatTheMi** [VeliML/MitsuRunner#43]
Hello together, 
after updating esphome to 2024.6.6, there occured several issues on compiling:

1. 
ota.unknown: [source secrets.yaml:23]
  'ota' requires a 'platform' key but it was not specified.
  password: xxxxxxx

add in file -> secrets.yaml 
in -> line 24: add **platform: esphome**

2.
  The "dallas" component has been replaced by the "one_wire" component.
  https://esphome.io/components/one_wire.
  - id: DS18B20_a
    pin:
      number: D2
      allow_other_uses: True
    update_interval: never
  - id: DS18B20_b
    pin:
      number: D2
      allow_other_uses: True
    update_interval: never

I'm already on my way to figure out, how to fix it. But not that coding-buddy, consequently not successful yet.

**Comment by Mits89** [comment]
Fix for the moment, use an older version of esphome: 

1. Windows-shell: pip3 install esphome==2024.5.5
2. Use the code as it is, from this github repository, until there is a fixed code available with the new one_wire

**Comment by iro70** [comment]
Fixed. 
New Mitsurunner code is compatible with ESPHome 2024.6.6 and later versions (and not compatible with previous ESPHome versions).
