### ISSUE TITLE
System HealthCheck

### ISSUE THREAD

**Issue by iro70** [VeliML/MitsuRunner#6]
Separate "HealthCheck.yaml" for long time (eg overnight) test to verify sufficient trouble-free operation of DS18B20 sensors and WiFi.
 * communication via COM/USB-port (optional WEB-server)
==> shows ErrorRates (failled/all DS18B20 readings) of each DS18B20 sensor over test period
==> shows max number of consecutive failed measurements of each DS18B20 (disturbance burst)
==> shows RSSI of wiFi signal (to ensure that Wifi connection is good enough)

Run this test once after the sensors are installed in their final positions before sulatusHuijaus activation (and then once and while).

**Comment by VeliML** [comment]
This is moved to improvement ideas board and closed from here.
