### ISSUE TITLE
Initial state not working properly yet

### ISSUE THREAD

**Issue by kestopuu** [VeliML/MitsuRunner#9]
For some reason, at least in my setup, after reset state goes always to the idle state, even defrost is active. If I set delta below zero by software, it goes to the defrost started state, but if reading acutal sensors, it doesn't.

I think first readings after boot are not working properly, so I think there should be added some kind of check that sensor readings are sane before deciding the first state after reset.

**Comment by VeliML** [comment]
This is probably fixed by my latest task. 
I changed place for the delay, so there is now initialization perioid, which is used to wait that everything from sensors/network connection to MQTT broker connections are established before system goes to follow state machine.

**Comment by VeliML** [comment]
I can not see any way how this could go to idle from reset state.

**Comment by VeliML** [comment]
This also fixes issue, if defrosting were just ending, while started the device:
 on_boot: 
  - switch.**turn_off**: gpio_relay

**Comment by VeliML** [comment]
I tested the logic twice with branch : VeliML-detect-wrong-defrosting-and-reset
The initial state detects correctly defrosting and goes to defrost state now without putting relay on.
